#!/bin/sh
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  SELECT 'CREATE DATABASE ${PAYLOAD_DB_NAME}'
  WHERE NOT EXISTS (
    SELECT FROM pg_database WHERE datname = '${PAYLOAD_DB_NAME}'
  )\gexec

  SELECT 'CREATE DATABASE ${N8N_DB_NAME}'
  WHERE NOT EXISTS (
    SELECT FROM pg_database WHERE datname = '${N8N_DB_NAME}'
  )\gexec

  GRANT ALL PRIVILEGES ON DATABASE ${PAYLOAD_DB_NAME} TO ${POSTGRES_USER};
  GRANT ALL PRIVILEGES ON DATABASE ${N8N_DB_NAME} TO ${POSTGRES_USER};
EOSQL
